package aula9;

public enum Constants {
	YES, NO, CURRENCY_EURO, CURRENCY_FL, DEBIT, EUR_CURRENCY_CODE, FL_CURRENCY_CODE, FL_CURRENCY_CODE_FOR_WEIRD_BANK, USD_CURRENCY_CODE, CREDIT, RBTT_BANK_ALTERNATE, DEBITING, TRUE, CREDITING;
}
